In [5]:
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[50, 64, 86,  9],
       [94, 18, 54, 62],
       [76, 23, 71, 78],
       [50, 62, 95, 84],
       [ 8, 72, 97, 32],
       [95, 28, 96, 41]])

In [6]:
a < 50

array([[False, False, False,  True],
       [False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [ True, False, False,  True],
       [False,  True, False,  True]])

In [9]:
a[(a > 50) & (a%2 == 0)]

array([64, 86, 94, 54, 62, 76, 78, 62, 84, 72, 96])

In [10]:
a[a% 7 != 0]

array([50, 64, 86,  9, 94, 18, 54, 62, 76, 23, 71, 78, 50, 62, 95,  8, 72,
       97, 32, 95, 96, 41])

In [22]:
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [15]:
actual

array([21, 44,  5, 49, 40, 21, 24, 28,  7, 33,  3, 15, 43, 26, 40, 13, 13,
       29,  2, 17, 40, 26, 31, 21, 21])

In [17]:
predicted

array([16,  8, 36, 30, 20, 21,  9, 23, 23,  4, 27, 23, 19, 36,  6, 24,  5,
       41,  2, 10, 46, 47, 18, 49, 15])

In [19]:
def mse(actual,predicted):
    return np.mean((actual - predicted)**2)

In [23]:
mse(actual,predicted)

515.0