In [23]:
import numpy as np
a = np.array([0,2,3,4,5],dtype = bool)
print(a)

[False  True  True  True  True]


In [30]:
np.zeros((3,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
np.random.random((3,4))

array([[0.82856692, 0.58248587, 0.10101877, 0.27917176],
       [0.55527799, 0.40151369, 0.6812046 , 0.74729611],
       [0.35764645, 0.11913819, 0.07296695, 0.37968443]])

In [46]:
np.arange(4,20).reshape(4,4)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])